// /*
//  * File generated by Test generator (dotup.dotup-vscode-test-generator)
//  * Date: 2019-11-17 10:02:52
// */
// import { expect } from 'chai';
// import { AuthGuard } from '../../../../app/core/guard/auth-guard';
// import { Injectable } from "@angular/core";
// import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, Router } from "@angular/router";
// import { Observable } from "rxjs";
// import { AuthService } from '../../../../app/core/services/auth.service';
// import { TOKEN } from "@shared/var/globals";

// describe('Test class AuthGuard', () => {

// it('AuthGuard-canActivate', () => {
// // Arguments
// const router1 = undefined;
// const authService1 = undefined;
// const next1 = undefined;
// const state1 = undefined;

// // Method call
// const authGuard = new AuthGuard(router1, authService1);
//  authGuard.canActivate(next1, state1);
// });

// });
