/*
 * File generated by Test generator (dotup.dotup-vscode-test-generator)
 * Date: 2019-11-17 09:43:55
*/
import { expect } from 'chai';
import { CloseDialogService } from '../../../../../app/core/services/emit/close-dialog.service';
import { Injectable, Output, EventEmitter } from "@angular/core";

describe('Test class CloseDialogService', () => {

it('CloseDialogService-closeDialog', () => {
// Arguments
const status1 = 'Oha';

// Method call
const closeDialogService = new CloseDialogService();
 closeDialogService.closeDialog(status1);
});

it('CloseDialogService-emitClose', () => {
// Arguments
const emitClose1 = undefined;

// Property call
const closeDialogService = new CloseDialogService();
closeDialogService.emitClose = emitClose1;
const result = closeDialogService.emitClose;

// Expect result
expect(result).equals(emitClose1);
});

});
