// /*
//  * File generated by Test generator (dotup.dotup-vscode-test-generator)
//  * Date: 2019-11-17 10:02:34
// */
// import { expect } from 'chai';
// import { GraphQLInterceptor } from '../../../../app/core/graphQL-interceptor/graphQL.Interceptor';
// import { HttpInterceptor, HttpRequest, HttpHandler } from "@angular/common/http";

// describe('Test class GraphQLInterceptor', () => {

// it('GraphQLInterceptor-intercept', () => {
// // Arguments
// const req1 = undefined;
// const next1 = undefined;

// // Method call
// const graphQLInterceptor = new GraphQLInterceptor();
//  graphQLInterceptor.intercept(req1, next1);
// });

// });
